-- Crear página dashboard-v2 en WordPress
INSERT INTO edgen_posts (
    post_author,
    post_date,
    post_date_gmt,
    post_content,
    post_title,
    post_excerpt,
    post_status,
    comment_status,
    ping_status,
    post_password,
    post_name,
    to_ping,
    pinged,
    post_modified,
    post_modified_gmt,
    post_content_filtered,
    post_parent,
    guid,
    menu_order,
    post_type,
    post_mime_type,
    comment_count
) VALUES (
    1,
    NOW(),
    UTC_TIMESTAMP(),
    '<!-- wp:shortcode -->\n[mostrar_dashboard_v2]\n<!-- /wp:shortcode -->',
    'Dashboard V2',
    '',
    'publish',
    'closed',
    'closed',
    '',
    'dashboard-v2',
    '',
    '',
    NOW(),
    UTC_TIMESTAMP(),
    '',
    0,
    'http://localhost:8080/?page_id=999',
    0,
    'page',
    '',
    0
);

SELECT CONCAT('✅ Página dashboard-v2 creada con ID: ', LAST_INSERT_ID()) as resultado;

